FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_BASE
ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE

COPY package*.json ./
RUN corepack enable
RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "dev"]